/**
 * Knowledge Graph — text utilities for zero-cost theme inference.
 *
 * Pure, local string processing (no AI/embeddings): tokenize post text +
 * article titles into salient terms, pull hashtags, and slugify. Used by
 * `themes.ts` to cluster saves by shared keyword/hashtag.
 */

/**
 * Common words to drop so themes surface real topics, not filler. A theme like
 * "Before" or "Actually" is noise — keep the bar high. Covers function words
 * plus high-frequency English verbs/adverbs/quantifiers/temporal words and
 * social-post noise. (Short topical acronyms like ai/llm/seo/rag/api survive —
 * they're length ≥ 2/3 and not listed here.)
 */
const STOPWORDS = new Set([
  // articles / conjunctions / prepositions / pronouns
  'the',
  'a',
  'an',
  'and',
  'or',
  'but',
  'if',
  'then',
  'else',
  'for',
  'nor',
  'so',
  'yet',
  'of',
  'to',
  'in',
  'on',
  'at',
  'by',
  'from',
  'with',
  'about',
  'as',
  'into',
  'like',
  'through',
  'after',
  'over',
  'between',
  'out',
  'up',
  'down',
  'off',
  'above',
  'below',
  'under',
  'again',
  'further',
  'once',
  'here',
  'there',
  'all',
  'any',
  'both',
  'each',
  'few',
  'more',
  'most',
  'other',
  'others',
  'some',
  'such',
  'no',
  'not',
  'only',
  'own',
  'same',
  'than',
  'too',
  'very',
  'can',
  'will',
  'just',
  'should',
  'now',
  'this',
  'that',
  'these',
  'those',
  'i',
  'you',
  'he',
  'she',
  'it',
  'we',
  'they',
  'them',
  'his',
  'her',
  'hers',
  'its',
  'our',
  'ours',
  'your',
  'yours',
  'their',
  'theirs',
  'my',
  'mine',
  'me',
  'us',
  'him',
  'what',
  'which',
  'who',
  'whom',
  'whose',
  'when',
  'where',
  'why',
  'how',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'having',
  'do',
  'does',
  'did',
  'doing',
  'would',
  'could',
  'should',
  'dont',
  'cant',
  'wont',
  'im',
  'ive',
  'youre',
  'theyre',
  'whats',
  'thats',
  'heres',
  'theres',
  'isnt',
  'arent',
  'wasnt',
  'werent',
  'hasnt',
  'havent',
  'didnt',
  'across',
  'against',
  'along',
  'among',
  'around',
  'because',
  'before',
  'behind',
  'beside',
  'beyond',
  'during',
  'except',
  'inside',
  'near',
  'onto',
  'outside',
  'since',
  'toward',
  'towards',
  'until',
  'upon',
  'within',
  'without',
  'whether',
  'while',
  'although',
  'though',
  'however',
  'therefore',
  'thus',
  'hence',
  'meanwhile',
  'anyway',
  'besides',
  'instead',
  'rather',
  // high-frequency verbs / adverbs / quantifiers / temporal
  'rt',
  'http',
  'https',
  'com',
  'www',
  'amp',
  'via',
  'new',
  'old',
  'get',
  'gets',
  'getting',
  'got',
  'gotten',
  'make',
  'makes',
  'made',
  'making',
  'want',
  'wants',
  'wanted',
  'need',
  'needs',
  'needed',
  'know',
  'knows',
  'knew',
  'known',
  'think',
  'thinks',
  'thought',
  'really',
  'real',
  'actually',
  'literally',
  'basically',
  'simply',
  'probably',
  'maybe',
  'perhaps',
  'certainly',
  'going',
  'goes',
  'gone',
  'went',
  'come',
  'comes',
  'came',
  'coming',
  'give',
  'gives',
  'gave',
  'given',
  'take',
  'takes',
  'took',
  'taken',
  'taking',
  'put',
  'puts',
  'keep',
  'keeps',
  'kept',
  'let',
  'lets',
  'find',
  'finds',
  'found',
  'feel',
  'feels',
  'felt',
  'look',
  'looks',
  'looked',
  'looking',
  'seem',
  'seems',
  'seemed',
  'show',
  'shows',
  'showed',
  'shown',
  'call',
  'calls',
  'called',
  'work',
  'works',
  'worked',
  'working',
  'use',
  'uses',
  'used',
  'using',
  'tell',
  'tells',
  'told',
  'ask',
  'asks',
  'asked',
  'try',
  'tries',
  'tried',
  'trying',
  'turn',
  'turns',
  'turned',
  'start',
  'starts',
  'started',
  'help',
  'helps',
  'helped',
  'built',
  'build',
  'builds',
  'run',
  'runs',
  'running',
  'said',
  'says',
  'say',
  'saying',
  'saw',
  'see',
  'sees',
  'seen',
  'seeing',
  'thing',
  'things',
  'stuff',
  'something',
  'someone',
  'anyone',
  'anything',
  'everyone',
  'everything',
  'nothing',
  'nobody',
  'people',
  'person',
  'time',
  'times',
  'today',
  'tomorrow',
  'yesterday',
  'day',
  'days',
  'week',
  'weeks',
  'month',
  'months',
  'year',
  'years',
  'hour',
  'hours',
  'minute',
  'minutes',
  'moment',
  'way',
  'ways',
  'lot',
  'lots',
  'bit',
  'kind',
  'sort',
  'type',
  'best',
  'better',
  'good',
  'great',
  'nice',
  'bad',
  'worse',
  'worst',
  'big',
  'small',
  'huge',
  'tiny',
  'high',
  'low',
  'long',
  'short',
  'also',
  'still',
  'even',
  'much',
  'many',
  'every',
  'always',
  'never',
  'often',
  'sometimes',
  'usually',
  'already',
  'almost',
  'enough',
  'quite',
  'pretty',
  'first',
  'second',
  'third',
  'last',
  'next',
  'final',
  'early',
  'late',
  'later',
  'soon',
  'ago',
  'one',
  'two',
  'three',
  'four',
  'five',
  'ten',
  'first',
  'another',
  'every',
  'each',
  'part',
  'full',
  'whole',
  'half',
  'top',
  'end',
  'right',
  'left',
  'sure',
  'okay',
  'yeah',
  'yep',
  'nope',
  'lol',
  'omg',
  'wow',
  'please',
  'thanks',
  'thank',
  'hey',
  'hi',
  'hello',
  'free',
  'plus',
  'less',
  'dont',
  'cant',
  'wont',
  'gonna',
  'wanna',
  'gotta',
  'etc',
  'ok',
  'different',
  'similar',
  'various',
  'certain',
  'particular',
  'specific',
  'general',
  'common',
  'simple',
  'easy',
  'hard',
  'its',
  'wasnt',
  'arent',
  'isnt',
  'couldnt',
  'wouldnt',
  'shouldnt',
  'didnt',
  'doesnt',
  'wont',
])

/**
 * Short tokens worth keeping as themes despite being < 4 chars — real topics in
 * a tech/AI-heavy collection. Also drives ALL-CAPS display in `titleCase`.
 */
export const TOPIC_ACRONYMS = new Set([
  'ai',
  'ml',
  'ar',
  'vr',
  'ui',
  'ux',
  'llm',
  'llms',
  'seo',
  'geo',
  'rag',
  'api',
  'apis',
  'gpu',
  'cpu',
  'css',
  'html',
  'sql',
  'aws',
  'gcp',
  'gpt',
  'nft',
  'dao',
  'defi',
  'saas',
  'b2b',
  'b2c',
  'cli',
  'sdk',
  'ios',
  'npm',
  'ssr',
  'dns',
  'ssl',
])

const URL_RE = /https?:\/\/\S+|t\.co\/\S+/gi
const HASHTAG_RE = /#(\w{2,30})/g
const WORD_RE = /[a-z][a-z0-9'+-]{1,}/g

/** Lowercase, strip urls + most punctuation; keep word characters + spaces. */
export function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .replace(URL_RE, ' ')
    .replace(/[^a-z0-9#'\s+-]/g, ' ')
}

/** Hashtags (without the #), lowercased, deduped, in first-seen order. */
export function extractHashtags(text: string): string[] {
  const out: string[] = []
  const seen = new Set<string>()
  let m: RegExpExecArray | null
  HASHTAG_RE.lastIndex = 0
  while ((m = HASHTAG_RE.exec(text)) !== null) {
    const tag = m[1].toLowerCase()
    if (!seen.has(tag)) {
      seen.add(tag)
      out.push(tag)
    }
  }
  return out
}

/**
 * Salient single-word terms from a blob of text: lowercased, length ≥ 3,
 * de-stopworded, not purely numeric. Deduped per call (document terms).
 */
export function tokenize(text: string): string[] {
  const norm = normalizeText(text)
  const out: string[] = []
  const seen = new Set<string>()
  let m: RegExpExecArray | null
  WORD_RE.lastIndex = 0
  while ((m = WORD_RE.exec(norm)) !== null) {
    // strip apostrophes so contractions normalize ("it's" → "its", "don't" →
    // "dont") and get caught by the stopword set instead of becoming themes
    const w = m[0].replace(/'/g, '')
    if (w.length < 3) continue
    if (STOPWORDS.has(w)) continue
    if (/^\d+$/.test(w)) continue
    if (!seen.has(w)) {
      seen.add(w)
      out.push(w)
    }
  }
  return out
}

/** Hashtags first (strong topic signal), then salient words. Deduped. */
export function salientTerms(text: string): string[] {
  const tags = extractHashtags(text)
  const words = tokenize(text)
  const seen = new Set(tags)
  const out = [...tags]
  for (const w of words) {
    if (!seen.has(w)) {
      seen.add(w)
      out.push(w)
    }
  }
  return out
}

/** URL/id-safe slug (lowercase, hyphenated, capped). */
export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32)
}

/** Title-case a term for a theme label. Known acronyms shout ("ai" → "AI"); a
 * normal short word capitalizes its first letter ("don" → "Don", not "DON"). */
export function titleCase(s: string): string {
  if (TOPIC_ACRONYMS.has(s)) return s.toUpperCase()
  return s.charAt(0).toUpperCase() + s.slice(1)
}
