/**
 * Tweet Test Fixtures
 *
 * Real FxTwitter API responses for snapshot testing.
 * Generated by: npx tsx scripts/fetch-tweet-fixtures.ts
 */

import textQuotingVideoData from './text-quoting-video.json'
import longText2ImagesData from './long-text-2-images.json'
import longText1ImageData from './long-text-1-image.json'
import quoteOfImageTweetData from './quote-of-image-tweet.json'
import quoteOfTextTweetData from './quote-of-text-tweet.json'
import videoTweetData from './video-tweet.json'
import longTextWithQuoteData from './long-text-with-quote.json'
import articleNoHeaderData from './article-no-header.json'
import articleWithMediaData from './article-with-media.json'
import plainTextData from './plain-text.json'
import fourImagesData from './4-images.json'
import emojiTweetData from './emoji-tweet.json'
import youtubeLinkData from './youtube-link.json'
import replyTweetData from './reply-tweet.json'

import type { FxTwitterResponse } from '@/lib/media/fxembed'

export const fixtures = {
  'text-quoting-video': textQuotingVideoData as unknown as FxTwitterResponse,
  'long-text-2-images': longText2ImagesData as unknown as FxTwitterResponse,
  'long-text-1-image': longText1ImageData as unknown as FxTwitterResponse,
  'quote-of-image-tweet': quoteOfImageTweetData as unknown as FxTwitterResponse,
  'quote-of-text-tweet': quoteOfTextTweetData as unknown as FxTwitterResponse,
  'video-tweet': videoTweetData as unknown as FxTwitterResponse,
  'long-text-with-quote': longTextWithQuoteData as unknown as FxTwitterResponse,
  'article-no-header': articleNoHeaderData as unknown as FxTwitterResponse,
  'article-with-media': articleWithMediaData as unknown as FxTwitterResponse,
  'plain-text': plainTextData as unknown as FxTwitterResponse,
  '4-images': fourImagesData as unknown as FxTwitterResponse,
  'emoji-tweet': emojiTweetData as unknown as FxTwitterResponse,
  'youtube-link': youtubeLinkData as unknown as FxTwitterResponse,
  'reply-tweet': replyTweetData as unknown as FxTwitterResponse,
} as const

export type FixtureSlug = keyof typeof fixtures

// Re-export individual fixtures
export const textQuotingVideo = textQuotingVideoData as unknown as FxTwitterResponse
export const longText2Images = longText2ImagesData as unknown as FxTwitterResponse
export const longText1Image = longText1ImageData as unknown as FxTwitterResponse
export const quoteOfImageTweet = quoteOfImageTweetData as unknown as FxTwitterResponse
export const quoteOfTextTweet = quoteOfTextTweetData as unknown as FxTwitterResponse
export const videoTweet = videoTweetData as unknown as FxTwitterResponse
export const longTextWithQuote = longTextWithQuoteData as unknown as FxTwitterResponse
export const articleNoHeader = articleNoHeaderData as unknown as FxTwitterResponse
export const articleWithMedia = articleWithMediaData as unknown as FxTwitterResponse
export const plainText = plainTextData as unknown as FxTwitterResponse
export const fourImages = fourImagesData as unknown as FxTwitterResponse
export const emojiTweet = emojiTweetData as unknown as FxTwitterResponse
export const youtubeLink = youtubeLinkData as unknown as FxTwitterResponse
export const replyTweet = replyTweetData as unknown as FxTwitterResponse

// Fixture metadata for iteration
export const fixtureMetadata = [
  { slug: 'text-quoting-video', author: 'swyx', tweetId: '2011861139689513314' },
  { slug: 'long-text-2-images', author: 'BasilTheGreat', tweetId: '2012044480556208542' },
  { slug: 'long-text-1-image', author: 'maverickecom', tweetId: '2011489837094683034' },
  { slug: 'quote-of-image-tweet', author: 'Nate_Google_', tweetId: '2011791917122547826' },
  { slug: 'quote-of-text-tweet', author: 'elonmusk', tweetId: '2012040892719169884' },
  { slug: 'video-tweet', author: 'Kekius_Sage', tweetId: '2011872260118716688' },
  { slug: 'long-text-with-quote', author: '_The_Prophet__', tweetId: '2011834234642841806' },
  { slug: 'article-no-header', author: 'aliniikk', tweetId: '2009347948816335031' },
  { slug: 'article-with-media', author: 'NoahRyanCo', tweetId: '2008957369212866843' },
  { slug: 'plain-text', author: 'TheCinesthetic', tweetId: '2010184900599583070' },
  { slug: '4-images', author: 'iamgdsa', tweetId: '2010782484728873387' },
  { slug: 'emoji-tweet', author: 'moonpay', tweetId: '2009626024968118554' },
  { slug: 'youtube-link', author: 'skalskip92', tweetId: '1996677567642996772' },
  { slug: 'reply-tweet', author: 'grok', tweetId: '2011596457824923855' },
] as const
