/* eslint-disable no-console */
/**
 * Fixture Fetcher Script
 *
 * Fetches FxTwitter API responses for test fixtures and saves them as JSON files.
 * Run with: npx tsx scripts/fetch-tweet-fixtures.ts
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Tweet fixtures with slugs and URLs
const FIXTURES = [
  { slug: 'text-quoting-video', author: 'swyx', id: '2011861139689513314' },
  { slug: 'long-text-2-images', author: 'BasilTheGreat', id: '2012044480556208542' },
  { slug: 'long-text-1-image', author: 'maverickecom', id: '2011489837094683034' },
  { slug: 'quote-of-image-tweet', author: 'Nate_Google_', id: '2011791917122547826' },
  { slug: 'quote-of-text-tweet', author: 'elonmusk', id: '2012040892719169884' },
  { slug: 'video-tweet', author: 'Kekius_Sage', id: '2011872260118716688' },
  { slug: 'long-text-with-quote', author: '_The_Prophet__', id: '2011834234642841806' },
  { slug: 'article-no-header', author: 'aliniikk', id: '2009347948816335031' },
  { slug: 'article-with-media', author: 'NoahRyanCo', id: '2008957369212866843' },
  { slug: 'plain-text', author: 'TheCinesthetic', id: '2010184900599583070' },
  { slug: '4-images', author: 'iamgdsa', id: '2010782484728873387' },
  { slug: 'emoji-tweet', author: 'moonpay', id: '2009626024968118554' },
  { slug: 'youtube-link', author: 'skalskip92', id: '1996677567642996772' },
  { slug: 'reply-tweet', author: 'grok', id: '2011596457824923855' },
]

const FIXTURES_DIR = path.join(__dirname, '../src/__tests__/fixtures/tweets')

async function fetchTweet(author: string, tweetId: string) {
  const url = `https://api.fxtwitter.com/${author}/status/${tweetId}`
  console.log(`Fetching: ${url}`)

  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`)
  }

  return response.json()
}

async function main() {
  console.log('Fetching tweet fixtures...\n')

  // Ensure directory exists
  if (!fs.existsSync(FIXTURES_DIR)) {
    fs.mkdirSync(FIXTURES_DIR, { recursive: true })
  }

  const results: { slug: string; success: boolean; error?: string }[] = []

  for (const fixture of FIXTURES) {
    try {
      const data = await fetchTweet(fixture.author, fixture.id)

      // Save raw FxTwitter response
      const filePath = path.join(FIXTURES_DIR, `${fixture.slug}.json`)
      fs.writeFileSync(filePath, JSON.stringify(data, null, 2))

      console.log(`  Saved: ${fixture.slug}.json`)
      results.push({ slug: fixture.slug, success: true })

      // Rate limit: wait 200ms between requests
      await new Promise((resolve) => setTimeout(resolve, 200))
    } catch (error) {
      console.error(`  Failed: ${fixture.slug} - ${error}`)
      results.push({ slug: fixture.slug, success: false, error: String(error) })
    }
  }

  // Generate index file
  const indexContent = `/**
 * Tweet Test Fixtures
 *
 * Real FxTwitter API responses for snapshot testing.
 * Generated by: npx tsx scripts/fetch-tweet-fixtures.ts
 */

${FIXTURES.map((f) => `import ${toCamelCase(f.slug)}Data from './${f.slug}.json'`).join('\n')}

export const fixtures = {
${FIXTURES.map((f) => `  '${f.slug}': ${toCamelCase(f.slug)}Data,`).join('\n')}
} as const

export type FixtureSlug = keyof typeof fixtures

// Re-export individual fixtures
${FIXTURES.map((f) => `export const ${toCamelCase(f.slug)} = ${toCamelCase(f.slug)}Data`).join('\n')}

// Fixture metadata
export const fixtureMetadata = ${JSON.stringify(
    FIXTURES.map((f) => ({
      slug: f.slug,
      author: f.author,
      tweetId: f.id,
      url: `https://x.com/${f.author}/status/${f.id}`,
    })),
    null,
    2
  )} as const
`

  fs.writeFileSync(path.join(FIXTURES_DIR, 'index.ts'), indexContent)
  console.log('\n  Generated: index.ts')

  // Summary
  console.log('\n--- Summary ---')
  const successful = results.filter((r) => r.success).length
  const failed = results.filter((r) => !r.success).length
  console.log(`Successful: ${successful}/${FIXTURES.length}`)
  if (failed > 0) {
    console.log(`Failed: ${failed}`)
    results
      .filter((r) => !r.success)
      .forEach((r) => console.log(`  - ${r.slug}: ${r.error}`))
  }
}

function toCamelCase(slug: string): string {
  return slug.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
}

main().catch(console.error)
